
project_id = "actvkmglkippzhzwzuzo"

[api]
enabled = true
port = 54321
swagger = true

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[realtime]
enabled = true

[functions.add-realtime-for-notifications]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-suspend-user]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true

[functions.admin-user-management]
verify_jwt = true

[functions.admin-bulk-create-users]
verify_jwt = true

[functions.admin-bulk-update-users]
verify_jwt = true

[functions.system-health-check]
verify_jwt = true
